PSAD\Bundle\APIBundle\Entity\Accpicture:
    type: entity
    table: accpicture
    id:
        nc:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        picaddress:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
        picdesc:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
