PSAD\Bundle\APIBundle\Entity\Breeder:
    type: entity
    table: breeder
    id:
        nc:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        breedcode:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
