PSAD\Bundle\APIBundle\Entity\Collector:
    type: entity
    table: collector
    id:
        nc:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ccode:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
        nc2:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
