PSAD\Bundle\APIBundle\Entity\Cooperator:
    type: entity
    table: cooperator
    id:
        ccode:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        insCode:
            type: string
            nullable: false
            length: 12
            fixed: false
            comment: ''
            column: ins_code
        iname:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
        fname:
            type: string
            nullable: false
            length: 15
            fixed: false
            comment: ''
        org:
            type: string
            nullable: false
            length: 120
            fixed: false
            comment: ''
        address:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
        cty:
            type: string
            nullable: false
            length: 3
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
