PSAD\Bundle\APIBundle\Entity\Cropname:
    type: entity
    table: cropname
    id:
        taxno2:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        commonname:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        comment:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
