PSAD\Bundle\APIBundle\Entity\Stock:
    type: entity
    table: stock
    id:
        nc:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        aWgt:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: a_wgt
        aSeed:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: a_seed
        aYear:
            type: date
            nullable: false
            comment: ''
            column: a_year
        aLocat:
            type: string
            nullable: false
            length: 12
            fixed: false
            comment: ''
            column: a_locat
        aDflag:
            type: string
            nullable: false
            length: 1
            fixed: true
            comment: ''
            column: a_dflag
        aVt:
            type: smallint
            nullable: true
            unsigned: false
            comment: ''
            column: a_vt
        aVtdate:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: a_vtdate
        s1000:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        s100:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        bLocat:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: b_locat
        notes:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
        duplsite:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
        storage:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
        vYear:
            type: string
            nullable: false
            length: 4
            fixed: false
            comment: ''
            column: v_year
        vSite:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
            column: v_site
        vLocation:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            column: v_location
        iDate:
            type: date
            nullable: false
            comment: ''
            column: i_date
        iSite:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
            column: i_site
        iLocation:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            column: i_location
        nc2:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        mousture:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
