PSAD\Bundle\APIBundle\Entity\Taxonchange:
    type: entity
    table: taxonchange
    id:
        nc:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        taxonOld:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
            column: taxon_old
        taxonNew:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
            column: taxon_new
        idDate:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: id_date
        idPerson:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: id_person
    lifecycleCallbacks: {  }
