PGR_search_homepage:
    pattern:  /
    defaults: { _controller: PGRSearchBundle:Search:index }

PGR_excel_export:
    pattern: /export_excel
    defaults: { _controller: PGRSearchBundle:Search:exportExcel }