PGR_search_homepage:
    pattern:  /{_locale}
    defaults: { _controller: PGRSearchBundle:Search:index, _locale: en }
    requirements:
        _locale: en|az

PGR_excel_export:
    pattern: /{_locale}/export_excel
    defaults: { _controller: PGRSearchBundle:Search:exportExcel, _locale: en }
    requirements:
        _locale: en|az

PGR_typeahead_taxons:
    pattern: /{_locale}/typeahead_taxa
    defaults: { _controller: PGRSearchBundle:Search:typeaheadTaxa, _locale: en}
    requirements:
        _locale: en|az

PGR_typeahead_families:
    pattern: /{_locale}/typeahead_families
    defaults: { _controller: PGRSearchBundle:Search:typeaheadFamilies, _locale: en}
    requirements:
        _locale: en|az

PGR_typeahead_species:
    pattern: /{_locale}/typeahead_species
    defaults: { _controller: PGRSearchBundle:Search:typeaheadSpecies, _locale: en}
    requirements:
        _locale: en|az

PGR_typeahead_genera:
    pattern: /{_locale}/typeahead_genera
    defaults: { _controller: PGRSearchBundle:Search:typeaheadGenera, _locale: en}
    requirements:
        _locale: en|az