parameters:
#    pgr_search.example.class: PGR\Bundle\SearchBundle\Example

services:
#    pgr_search.example:
#        class: %pgr_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
