parameters:
#    psadapi.example.class: PSAD\Bundle\APIBundle\Example

services:
#    psadapi.example:
#        class: %psadapi.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
