pgr_api:
    resource: "@PGRAPIBundle/Resources/config/routing.yml"
    prefix:   /

pgr_search:
    resource: "@PGRSearchBundle/Resources/config/routing.yml"
    prefix:   /

rest:
    type: rest
    resource: "routing_rest.yml"
    prefix: /api

